### ISSUE TITLE
Use new leader elections features in Juju

### ISSUE THREAD

**Issue by whitmo** [mbruzek/consul-charm#1]
This charm still uses a peer based leader election scheme that would be greatly simplified by using leader election.

**Comment by mbruzek** [comment]
After evaluating the Juju leader election feature, and reading more about Consul's own raft leader election process, I made the decision to use bootstrap-expect with the number of expected nodes in the cluster.  This allows Consul to elect its own leader.  The code for this is in PR #4 which satisfies this issue.
